using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SkeletonAnnos : MonoBehaviour
{
    // Start is called before the first frame update
    public GameObject EyeSocketLabel;
    public GameObject EyeSocketInfo;

    public GameObject CraniumLabel;
    public GameObject CraniumInfo;

    //public GameObject TeethLabel;
    //public GameObject TeethInfo;

    public GameObject CervicalLabel;
    public GameObject CervicalInfo;

   // public GameObject ClavicleLabel;
    //public GameObject ClavicleInfo;

    public GameObject ScapulaLabel;
    public GameObject ScapulaInfo;

    public GameObject SternumLabel;
    public GameObject SternumInfo;

   // public GameObject TrueRibsLabel;
    //public GameObject TrueRibsInfo;

    //public GameObject FloatingRibsLabel;
    //public GameObject FloatingRibsInfo;

    //public GameObject LumbarLabel;
    //public GameObject LumbarInfo;

    //public GameObject RadiusLabel;
    //public GameObject RadiusInfo;

    //public GameObject UlnaLabel;
    //public GameObject UlnaInfo;

    //public GameObject IlliumLabel;
    //public GameObject IlliumInfo;

    public GameObject SacrumLabel;
    public GameObject SacrumInfo;

    //public GameObject CoccyxLabel;
    //public GameObject CoccyxInfo;

    //public GameObject PubisLabel;
    //public GameObject PubisInfo;

   // public GameObject IschiumLabel;
    //public GameObject IschiumInfo;

    //public GameObject FemurLabel;
    //public GameObject FemurInfo;

    public GameObject PatellaLabel;
    public GameObject PatellaInfo;

    public GameObject TibiaLabel;
    public GameObject TibiaInfo;

    public GameObject FibulaLabel;
    public GameObject FibulaInfo;

    public GameObject TarsalsLabel;
    public GameObject TarsalsInfo;

    //public GameObject MetatarsalsLabel;
    //public GameObject MetatarsalsInfo;

    //public GameObject PhalangesALabel;
    //public GameObject PhalangesAInfo;

    //public GameObject CarpalsLabel;
    //public GameObject CarpalsInfo;

    //public GameObject MetacarpalsLabel;
    //public GameObject MetacarpalsInfo;

    //public GameObject PhalangesBLabel;
    //public GameObject PhalangesBInfo;

    //public GameObject HumerusLabel;
    //public GameObject HumerusInfo;


    public GameObject MenuObj;
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
       
    }
    void OnMouseDown()
    {
        //ZAcube
        if (gameObject.name == "EyeSocket")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
            MenuObj.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Cranium")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
            MenuObj.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Teeth")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
            MenuObj.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "CervicalVerterbra")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
            MenuObj.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Clavicle")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Scapula")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Sternum")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "TrueRibs")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "FloatingRibs")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "LumbarVertebra")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Radius")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Ulna")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Illium")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Sacrum")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Coccyx")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Pubis")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Ischium")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Femur")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Patella")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Tibia")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Fibula")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Tarsals")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Metatarsals")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "PhalangesA")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Carpals")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Metacarpals")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "PhalangesB")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }

        //ZAcube
        if (gameObject.name == "Humerus")
        {
            EyeSocketLabel.SetActive(true);
            EyeSocketInfo.SetActive(true);
            CraniumLabel.SetActive(false);
            CraniumInfo.SetActive(false);
            //TeethLabel.SetActive(false);
            //TeethInfo.SetActive(false);
            CervicalLabel.SetActive(false);
            CervicalInfo.SetActive(false);
            //ClavicleLabel.SetActive(true);
            //ClavicleInfo.SetActive(true);
            ScapulaLabel.SetActive(false);
            ScapulaInfo.SetActive(false);
            SternumLabel.SetActive(false);
            SternumInfo.SetActive(false);
            //TrueRibsLabel.SetActive(false);
            //TrueRibsInfo.SetActive(false);
            //LumbarLabel.SetActive(false);
            //LumbarInfo.SetActive(false);
            //RadiusLabel.SetActive(false);
            //RadiusInfo.SetActive(false);
            //UlnaLabel.SetActive(false);
            //UlnaInfo.SetActive(false);
            //IlliumLabel.SetActive(false);
            //IlliumInfo.SetActive(false);
            SacrumLabel.SetActive(false);
            SacrumInfo.SetActive(false);
            //CoccyxLabel.SetActive(false);
            //CoccyxInfo.SetActive(false);
            //PubisLabel.SetActive(false);
            //PubisInfo.SetActive(false);
            //IschiumLabel.SetActive(false);
            //IschiumInfo.SetActive(false);
            //FemurLabel.SetActive(false);
            //FemurInfo.SetActive(false);
            PatellaLabel.SetActive(false);
            PatellaInfo.SetActive(false);
            TibiaLabel.SetActive(false);
            TibiaInfo.SetActive(false);
            FibulaLabel.SetActive(false);
            FibulaInfo.SetActive(false);
            TarsalsLabel.SetActive(false);
            TarsalsInfo.SetActive(false);
            //MetatarsalsLabel.SetActive(false);
            //MetatarsalsInfo.SetActive(false);
            //PhalangesALabel.SetActive(false);
            //PhalangesAInfo.SetActive(false);
            //CarpalsLabel.SetActive(false);
            //CarpalsInfo.SetActive(false);
            //MetacarpalsLabel.SetActive(false);
            //MetacarpalsInfo.SetActive(false);
            //PhalangesBLabel.SetActive(false);
            //PhalangesBInfo.SetActive(false);
            //HumerusLabel.SetActive(false);
            //HumerusInfo.SetActive(false);
        }


         
    }



}
